version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: chess_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: chess_insights
      MYSQL_USER: chess
      MYSQL_PASSWORD: chesspass
    ports:
      - "3307:3306"

  redis:
    image: redis:7
    container_name: chess_redis
    ports:
      - "6379:6379"
